### PR TITLE
Update pub.dev links

### PR DESCRIPTION
**Pull request by nohli**
With this PR, the right section on pub.dev will show the View/report issues link to GitHub, like [here](https://pub.dev/packages/android_id) (the show-logic was recently changed).

### CODE REVIEW

**Comment by gskinner** [comment]
While an appropriate change, this reeks of PR farming. Can you explain why there's a co-author on a one line change?

**Comment by nohli** [comment]
Yesterday, we had a Flutter dojo about using `flutter_animate` and during reading the docs, we saw that it says 'homepage' instead of 'repository' (and 'issues').
In our team, we have the convention of tagging our coworkers when we do pair programming.
But I kind of feel I shouldn't have to explain why I contribute to an open source project.

**Comment by gskinner** [comment]
Hi Nohli — I appreciate you taking the time to respond, and apologize if I came off as ungrateful. I definitely wasn't asking you to explain why you'd contribute to open-source, I just didn't understand why a one-line contribution would have a co-author. Your explanation makes total sense, and wasn't something I had considered.

I'm not sure how much of a issue it still is, but there used to be a minor industry of making minimal effort PRs and tagging in as many people as possible to "farm" activity — obviously not what you were doing, but hopefully you can see why this perked my ears up. :)

Anyway, thanks for the PR! Accepted.

**Comment by nohli** [comment]
Hey @gskinner, thanks for replying 🙂
I wonder what these people get from farming, as it would still mean effort to open all those PRs.

Thanks for merging. We loved your package and created many animations that each group presented.
Especially sliding in widgets when first opening a page could be beneficial for almost all UIs 🙂 

There was one issue (possible bug?): When chaining animations and setting a delay in one, the other chained animations are affected as well. Is it supposed to behave like this? (FYI our group used version `1.0.0` from pub.dev - maybe it's already changed on `main`).

**Comment by gskinner** [comment]
Hi Nohli - PR farming is mainly to make your account look super active for hiring purposes, and so devs can say "I contributed to 100 repos including these popular ones", even though all they did was fix a typo or something. I used to have it happen a lot in another repo I ran, which is why I'm a little cautious about it now.

I'm really happy to hear you and your team enjoy the library!

From the README, regarding delay, duration, and curve: "If not specified (or null), these values are inherited from the previous effect". The general idea is that this lets you layer effects without having to duplicate all the timing info.

```
foo.animate()
  .scale(duration: 1000.ms).fadeIn(curve: Curves.easeInOut)
  .then(delay: 700.ms)
  .fadeOut()
```

This example takes advantage of this inheritance feature in a number of ways:

- `scale`, `fadeIn` and `fadeOut` all share the same duration, instead of having to redefine it for each
- `fadeIn` and `fadeOut` share the same curve
- `then` works by setting the new inheritable delay to the end of the previous effect plus the specified additional delay. So `fadeOut` inherits a delay of 1700 ms (runs 700ms after fadeIn ends).

My hope is that while this functionality is perhaps a touch esoteric when you first encounter it, the benefits it provides are significant enough to make it worth it.

Of course, you can also just be explicit and always define delay, duration, curve on each effect if you don't want the "magic" inheritance. :)

Feedback is always welcome.

**Comment by nohli** [comment]
Thanks a lot 🙏🏽😊

Makes a lot of sense, like the extension on int (for duration) which is super intuitive.

We'll happily use your package in our apps 💪🏽

**Pull request merged**
