### PR TITLE
feat: add quadratic bezier effect

### PR DESCRIPTION
**Pull request by drown0315**
## Describe
Add a bezier curve effect.
The implementation is based on a quadratic bezier curve.

## The final result

https://user-images.githubusercontent.com/108989782/230714858-33f37b59-7831-4612-ac64-36c9b98e4ef9.mp4

### CODE REVIEW

**Comment by gskinner** [comment]
Great addition. Life is a bit busy at the moment, but I will aim to review this as soon as I can.

**Comment by gskinner** [comment]
I've been thinking about this a little bit, and have you considered using a Path instead? That would facilitate multi-curve paths, arcs, and handy methods like `arcTo`, `cubicTo`, etc.

I believe you could use `computeMetrics` in combination with `PathMetric.getTangentForOffset` to make this quite simple. It would even allow you to provide an option to rotate the target to follow the path.

Something like this:
``` dart
Path myPath = Path()..moveTo(10, 10)..cubicTo(/* etc */);
foo.animate()
  .followPath(path: myPath, rotate: true, rotationOffset: pi / 2)
```

`Path` supports multiple paths (returned by `computeMetrics`), so you'd need to document that only the first one will be used.

**Comment by gskinner** [comment]
Closing this in favor of `FollowPathEffect`, which I just committed. It supports arbitrary multi-segment paths, plus rotation.

Thanks for the great idea for an addition! Testing is very welcome.

PathEffect

**Comment by drown0315** [comment]
Look great, thank you for the new feature.

**Pull request closed without merging**
